// Isolated register-block event priority tests. Engine events are controlled
// directly so a new event can coincide exactly with a registered clear pulse.
`timescale 1ns/1ps
module regs_event_test;
  import dma_pkg::*;
  logic clk = 0;
  always #5 clk = ~clk;
  logic rst_n = 0;
  axil_if axil(clk, rst_n);
  logic [31:0] src, dst, len;
  logic irq_en, start_req, done, err;
  logic start_accept = 0, set_done = 0, set_err = 0;
  logic [7:0] event_code = 0;
  dma_regs_axil dut (
    .clk(clk), .rst_n(rst_n),
    .s_axil_awaddr(axil.awaddr), .s_axil_awprot(axil.awprot),
    .s_axil_awvalid(axil.awvalid), .s_axil_awready(axil.awready),
    .s_axil_wdata(axil.wdata), .s_axil_wstrb(axil.wstrb),
    .s_axil_wvalid(axil.wvalid), .s_axil_wready(axil.wready),
    .s_axil_bresp(axil.bresp), .s_axil_bvalid(axil.bvalid), .s_axil_bready(axil.bready),
    .s_axil_araddr(axil.araddr), .s_axil_arprot(axil.arprot),
    .s_axil_arvalid(axil.arvalid), .s_axil_arready(axil.arready),
    .s_axil_rdata(axil.rdata), .s_axil_rresp(axil.rresp),
    .s_axil_rvalid(axil.rvalid), .s_axil_rready(axil.rready),
    .cfg_src_addr(src), .cfg_dst_addr(dst), .cfg_len_bytes(len), .cfg_irq_en(irq_en),
    .start_req_pulse(start_req), .engine_busy(1'b0), .engine_bytes_remain(32'd0),
    .start_accept_pulse(start_accept), .set_done_pulse(set_done), .set_err_pulse(set_err),
    .err_code_value(event_code), .sticky_done(done), .sticky_err(err)
  );
  task automatic read_expect(input logic [31:0] address, input logic [31:0] expected);
    @(negedge clk); axil.araddr = address; axil.arvalid = 1;
    do @(posedge clk); while (!axil.arready);
    @(negedge clk); axil.arvalid = 0;
    if (axil.rvalid !== 1 || axil.rresp !== 0 || axil.rdata !== expected)
      $fatal(1, "CSR addr=%h expected=%h actual=%h valid=%b resp=%b", address, expected,
        axil.rdata, axil.rvalid, axil.rresp);
    @(negedge clk);
  endtask
  task automatic pulse_events(input bit d, e, a, input logic [7:0] code);
    @(negedge clk); set_done = d; set_err = e; start_accept = a; event_code = code;
    @(negedge clk); set_done = 0; set_err = 0; start_accept = 0;
  endtask
  task automatic write_event(input logic [31:0] address, data,
                             input bit simultaneous_done, simultaneous_err,
                             input logic [7:0] code);
    bit aw_done, w_done;
    @(negedge clk); axil.awaddr = address; axil.awvalid = 1;
    axil.wdata = data; axil.wvalid = 1;
    aw_done = 0; w_done = 0;
    while (!aw_done || !w_done) begin
      @(posedge clk);
      if (axil.awvalid && axil.awready) aw_done = 1;
      if (axil.wvalid && axil.wready) w_done = 1;
      @(negedge clk);
      if (aw_done) axil.awvalid = 0;
      if (w_done) axil.wvalid = 0;
    end
    if (axil.bvalid !== 1 || axil.bresp !== 0) $fatal(1, "CSR write failed");
    // Clear pulses generated by the committed write take effect on the next
    // rising edge; the injected engine event is sampled on that same edge.
    set_done = simultaneous_done; set_err = simultaneous_err; event_code = code;
    @(negedge clk); set_done = 0; set_err = 0;
  endtask
  task automatic check_events(input logic [31:0] irq_status, code);
    read_expect(REG_OFF_IRQ_STATUS, irq_status);
    read_expect(REG_OFF_STATUS, irq_status << 1);
    read_expect(REG_OFF_ERR_CODE, code);
  endtask
  initial begin
    axil.awaddr = 0; axil.awprot = 0; axil.awvalid = 0;
    axil.wdata = 0; axil.wstrb = 4'hf; axil.wvalid = 0; axil.bready = 1;
    axil.araddr = 0; axil.arprot = 0; axil.arvalid = 0; axil.rready = 1;
    repeat (3) @(negedge clk); rst_n = 1;
    check_events(0, 0);
    pulse_events(1, 1, 0, ERR_AXI_RRESP);
    check_events(3, ERR_AXI_RRESP);
    write_event(REG_OFF_IRQ_STATUS, 2, 0, 0, 0);
    check_events(1, ERR_AXI_RRESP); // IRQ RW1C preserves the diagnostic code.
    pulse_events(0, 1, 0, ERR_AXI_BRESP);
    write_event(REG_OFF_CTRL, 32'ha, 0, 0, 0);
    check_events(1, ERR_NONE); // CTRL.CLR_ERR clears the diagnostic code.
    if (irq_en !== 1) $fatal(1, "CTRL IRQ enable changed unexpectedly");
    write_event(REG_OFF_IRQ_STATUS, 3, 1, 1, ERR_AXI_RRESP);
    check_events(3, ERR_AXI_RRESP); // New event wins over simultaneous RW1C.
    write_event(REG_OFF_CTRL, 32'hc, 1, 1, ERR_AXI_BRESP);
    check_events(3, ERR_AXI_BRESP); // New event wins over CTRL clear as well.
    pulse_events(1, 1, 1, ERR_AXI_PROTO);
    check_events(3, ERR_AXI_PROTO); // New event wins over accepted START clear.
    pulse_events(0, 0, 1, 0);
    check_events(0, 0);
    write_event(REG_OFF_SRC_ADDR, 32'h100, 0, 0, 0);
    write_event(REG_OFF_DST_ADDR, 32'h200, 0, 0, 0);
    write_event(REG_OFF_LEN, 32'h80, 0, 0, 0);
    write_event(REG_OFF_CTRL, 2, 0, 0, 0);
    pulse_events(1, 1, 0, ERR_AXI_RRESP);
    @(negedge clk); rst_n = 0; set_done = 1; set_err = 1; start_accept = 1;
    repeat (2) @(negedge clk);
    if ({src, dst, len, irq_en, done, err, start_req, axil.bvalid, axil.rvalid} !== 0)
      $fatal(1, "Reset did not clear configuration/events/responses");
    set_done = 0; set_err = 0; start_accept = 0; rst_n = 1;
    check_events(0, 0);
    read_expect(REG_OFF_CTRL, 0);
    read_expect(REG_OFF_SRC_ADDR, 0);
    read_expect(REG_OFF_DST_ADDR, 0);
    read_expect(REG_OFF_LEN, 0);
    $display("UNIT_PASS regs_event RW1C/code/CTRL/set-priority/start/reset");
    $finish;
  end
  initial begin
    repeat (1000) @(negedge clk);
    $fatal(1, "Register event unit test timed out");
  end
endmodule
